name: map_values
description: Objeto para mapear chaves valores.
version: 0.0.1
author: Altamir altamir.benkenstein@gmail.com <altamir.benkenstein@gmail.com>
homepage: https://github.com/Altamir/flutter_map_values

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: